### ISSUE TITLE
Error at "RUN apk add --update --no-progress make python bash" in  Docker file.

### ISSUE THREAD

**Issue by JeongJun-Lee** [duluca/lemon-mart-server#28]
=> ERROR [ 2/11] RUN apk add --update --no-progress make python bash                                          9.2s
------                                                                                                              
 > [ 2/11] RUN apk add --update --no-progress make python bash:                                                     
#6 0.333 fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz                              
#6 4.283 fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz                         
#6 8.891 ERROR: unable to select packages:                                                                          
#6 8.957   python (no such package):
#6 8.957     required by: world[python]
------
executor failed running [/bin/sh -c apk add --update --no-progress make python bash]: exit code: 1
ERROR: Service 'server' failed to build : Build failed

**Comment by duluca** [comment]
Didn't observe the error after the recent updates. The build passes on CircleCI.
